### PR TITLE
Add User ID and Group ID modification

### PR DESCRIPTION
**Pull request by stormbyte**
### Description
Add the possibility to modify the user and group ID of de www-data user inside the container.
This will create the functionality to match the operating user of the main system.
Allowing the Main system to edit the files without changing the permissions.

### Related issues
Non

### CODE REVIEW

**Comment by karensg** [comment]
This is actually beautiful. Would be great to see this in the main as well.

**Comment by ammannbe** [comment]
This fix don't work anymore and has multiple conflicts.
Is there another solution to map the local UID and GID?

**Comment by jawys** [comment]
What about this? https://docs.docker.com/engine/security/userns-remap/

**Comment by ammannbe** [comment]
I tried to remap the user but it doesn't seem to work either:
```json
{
  "userns-remap": "myuser"
}
```

I like the solution of [laravel/sail](https://laravel.com/docs/10.x/sail). They are able to map the local UID/GID automatically - and to override is also possible of course.

They have a [startup/entrypoint](https://github.com/laravel/sail/blob/1.x/runtimes/8.0/start-container) script which makes a `usermod`'s the applications user ID (in craft cms case this would be nginx).

Unfortunately I wasn't able to recreate something like that on my system (probably it has to do with the docker context I didn't get).

But I was able to create a custom image with hardcoded values:

```Dockerfile
FROM craftcms/nginx:8.2-dev

USER root

RUN set -ex \
    && apk upgrade --no-cache \
    && apk add --no-cache \
        shadow

RUN usermod -u 1000 www-data && groupmod -g 1000 www-data

RUN chown www-data /run/nginx.pid
RUN chown www-data /run/supervisord.pid
RUN chown -R www-data:www-data /var/lib/nginx/

USER www-data
```

My knowledge about docker is limited, so I'm not sure what would be the best solution to adjust the current implementation - and how to exactly build the `craftcms/docker` project itself on my system locally.

**Comment by ammannbe** [comment]
Nevermind, I've created a fork from laravel/sail and adjusted it so it works with craft perfectly.
https://github.com/ammannbe/craft-sail

**Pull request closed without merging**
