### PR TITLE
Fix missing localisation options in clean installs

### PR DESCRIPTION
**Pull request by SHoogland**
### Description

Should fix the missing localisation issues according to https://github.com/craftcms/docker/issues/59#issuecomment-1153741081

### Related issues
#59 
#60

### CODE REVIEW

**Comment by thijskaspers** [comment]
Thanks for creating the PR @SHoogland !

We might have to force the PHP image to Alpine 3.16 or newer as well, as the `icu-data-full` package is only available from 3.16 and up. See https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.16.0. If people build the image while their Alpine Linux version still has 3.15 in the build cache, it might fail with a message that the `icu-data-full` package can't be found.

@timkelty what's your take on this? Also see this issue in the PHP docker image repo for more information on the subject: https://github.com/docker-library/php/issues/1302#issuecomment-1155497591

**Review by thijskaspers — CHANGES_REQUESTED** [review]
The `iconv-build` is a separate Docker "multi-stage" build layer. That is not the PHP image that is used for the build. The line that needs to be changed to pin PHP to a newer Alpine Linux version is line 8, where it says:

`FROM php:${PHP_VERSION}-${PROJECT_TYPE}-alpine`

That one has to be changed to:

`FROM php:${PHP_VERSION}-${PROJECT_TYPE}-alpine3.16`

This will pin it to Alpine 3.16 where `icu-data-full` is available as a package. Also see https://hub.docker.com/_/php?tab=tags&page=1&name=alpine for the available Alpine tags in the official PHP docker images repo.

**Comment by thijskaspers** [comment]
By the way, this issue is present in all PHP versions, so it will also have to be updated at Dockerfile 7.3, 7.4 and 8.0 😅

**Comment by timkelty** [comment]
Looking into this today, stay tuned!

**Comment by bruno-canada** [comment]
As a temporary solution, I have built the `craftcms/php-fpm:8.0` container with the following customization:

```
RUN apk update \
        && apk add icu-dev icu-data-full \
        && docker-php-ext-configure intl \
        && docker-php-ext-install intl \
        && apk add --no-cache $PHPIZE_DEPS 
```

Worked fine.

**Comment by timkelty** [comment]
> Edit: for PHP 7.3 the newest Alpine Build is 3.15 (3.16 doesn't exist), so that one has to be pinned to 3.15 without the need for the `icu-data-full` package. See: https://hub.docker.com/_/php?tab=tags&page=1&name=7.3-fpm-alpine

Actually, I just removed 7.3 from builds going forward. We try to match what https://github.com/docker-library/php is doing in that regard, and they are only building 7.4 and up currently.

**Comment by timkelty** [comment]
Fixed this, but not with this commit. Nonetheless, thanks @SHoogland.

**Pull request closed without merging**
